<?php

namespace App\Notification;

use Twig\Environment;
use App\Entity\Contact;

class ContactNotification {

    private $twig;
    private $mailer;
    public function __construct(\Swift_Mailer $mailer, Environment $twig){
        $this->twig = $twig;
        $transport = (new \Swift_SmtpTransport('smtp.mailtrap.io', 2525))
                    ->setUsername('6fcdcd3b5adc4b') // generated by Mailtrap
                    ->setPassword('7bf7f55e5824f6'); // generated by Mailtrap

        $this->mailer = new \Swift_Mailer($transport);
        //$this->mailer = $mailer;
    }
    public function notify(Contact $contact) {
        //dump($this->mailer);
        //die();
        $message = (new \Swift_Message('Dadch&Co.com: '. $contact->getSujet()))
                    ->setFrom($contact->getEmail())
                    ->setTo('ydiaw@dadch-co.com')
                    ->setReplyTo($contact->getEmail())
                    ->setBody($this->twig->render('emails/contact.html.twig', ['contact' => $contact]), 'text/html');
        $this->mailer->send($message);
    }
}